
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: currencyservice
  description: This service provides functionality to convert amounts between different currencies.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/codilime/opentelemetry.io/tree/main/content/en/docs/demo/services/currency
    github.com/project-slug: codilime/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
