
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  description: All generated metrics and exemplars are scraped by Prometheus.
  annotations:
    github.com/project-slug: codilime/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
