
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paymentservice
  description: This service is responsible to process credit card payments for orders. It will return an error if the credit card is invalid or the payment can not be processed.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/codilime/opentelemetry.io/tree/main/content/en/docs/demo/services/payment
    github.com/project-slug: codilime/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
