
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: This service is responsible to show metrics.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/codilime/opentelemetry.io/tree/main/content/en/docs/demo/services/grafana
    github.com/project-slug: codilime/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
